import { useState, useEffect } from 'react';
import api from '../api/axios';
import { Key, Plus, Copy, Check, Clock, User, Filter } from 'lucide-react';

const AccessCodes = () => {
    const [codes, setCodes] = useState([]);
    const [loading, setLoading] = useState(true);
    const [copiedId, setCopiedId] = useState(null);
    const [showModal, setShowModal] = useState(false);
    const [pagination, setPagination] = useState({
        page: 1,
        limit: 10,
        total: 0,
        totalPages: 0
    });
    const [newCodeData, setNewCodeData] = useState({
        targetRole: 'technician',
        expiresInDays: 7
    });

    useEffect(() => {
        fetchCodes();
    }, [pagination.page]);

    const fetchCodes = async () => {
        setLoading(true);
        try {
            const res = await api.get(`/access-codes?page=${pagination.page}&limit=${pagination.limit}`);
            setCodes(res.data.data);
            setPagination(prev => ({
                ...prev,
                total: res.data.total,
                totalPages: res.data.totalPages
            }));
        } catch (err) {
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    const handleGenerate = async (e) => {
        e.preventDefault();
        try {
            await api.post('/access-codes', newCodeData);
            fetchCodes();
            setShowModal(false);
        } catch (err) {
            alert('Failed to generate code');
        }
    };

    const handlePageChange = (newPage) => {
        if (newPage >= 1 && newPage <= pagination.totalPages) {
            setPagination(prev => ({ ...prev, page: newPage }));
        }
    };

    const copyToClipboard = (text, id) => {
        navigator.clipboard.writeText(text);
        setCopiedId(id);
        setTimeout(() => setCopiedId(null), 2000);
    };

    return (
        <div className="space-y-6 pb-20">
            <div className="flex justify-between items-end">
                <div>
                    <h1 className="text-2xl font-bold">Access Codes</h1>
                    <p className="text-slate-500">Generate and manage access codes for Technicians and Shops</p>
                </div>
                <button
                    onClick={() => setShowModal(true)}
                    className="bg-blue-600 text-white px-6 py-2 rounded-xl font-medium shadow-lg shadow-blue-600/20 hover:bg-blue-500 transition-all flex items-center gap-2"
                >
                    <Plus size={20} />
                    <span>Generate New Code</span>
                </button>
            </div>

            <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
                <div className="overflow-x-auto">
                    <table className="w-full text-left">
                        <thead className="bg-slate-50 text-slate-500 text-sm uppercase">
                            <tr>
                                <th className="px-6 py-4 font-semibold">Access Code</th>
                                <th className="px-6 py-4 font-semibold">Target Role</th>
                                <th className="px-6 py-4 font-semibold">Status</th>
                                <th className="px-6 py-4 font-semibold">Expires At</th>
                                <th className="px-6 py-4 font-semibold">Generated By</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100">
                            {loading ? (
                                <tr><td colSpan="5" className="p-10 text-center text-slate-400">Loading codes...</td></tr>
                            ) : codes.length === 0 ? (
                                <tr><td colSpan="5" className="p-10 text-center text-slate-400">No access codes found</td></tr>
                            ) : codes.map((item) => (
                                <tr key={item._id} className="hover:bg-slate-50/50 transition-colors">
                                    <td className="px-6 py-4">
                                        <div className="flex items-center gap-2">
                                            <code className="bg-slate-100 px-3 py-1 rounded-lg font-mono font-bold text-blue-600 text-lg">
                                                {item.code}
                                            </code>
                                            <button
                                                onClick={() => copyToClipboard(item.code, item._id)}
                                                className="p-1.5 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded"
                                            >
                                                {copiedId === item._id ? <Check size={16} className="text-emerald-500" /> : <Copy size={16} />}
                                            </button>
                                        </div>
                                    </td>
                                    <td className="px-6 py-4">
                                        <span className={`px-3 py-1 rounded-full text-xs font-bold capitalize ${item.targetRole === 'technician' ? 'bg-orange-100 text-orange-700' : 'bg-emerald-100 text-emerald-700'
                                            }`}>
                                            {item.targetRole}
                                        </span>
                                    </td>
                                    <td className="px-6 py-4">
                                        {item.isUsed ? (
                                            <span className="text-slate-400 text-sm flex items-center gap-1">
                                                <Check size={14} /> Used
                                            </span>
                                        ) : new Date(item.expiresAt) < new Date() ? (
                                            <span className="text-red-400 text-sm flex items-center gap-1">
                                                <Clock size={14} /> Expired
                                            </span>
                                        ) : (
                                            <span className="text-emerald-500 text-sm flex items-center gap-1 font-medium">
                                                <div className="w-1.5 h-1.5 bg-emerald-500 rounded-full animate-pulse" /> Active
                                            </span>
                                        )}
                                    </td>
                                    <td className="px-6 py-4 text-slate-600 text-sm">
                                        {new Date(item.expiresAt).toLocaleDateString()}
                                    </td>
                                    <td className="px-6 py-4 text-slate-600 text-sm">
                                        <div className="flex items-center gap-2">
                                            <User size={14} className="opacity-50" />
                                            {item.generatedBy?.firstName || 'System'}
                                        </div>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>

                {/* Pagination Controls */}
                <div className="bg-slate-50 px-6 py-4 flex items-center justify-between border-t border-slate-200">
                    <div className="text-sm text-slate-500">
                        Showing <span className="font-medium text-slate-700">{codes.length}</span> of <span className="font-medium text-slate-700">{pagination.total}</span> codes
                    </div>
                    <div className="flex items-center gap-2">
                        <button
                            onClick={() => handlePageChange(pagination.page - 1)}
                            disabled={pagination.page === 1}
                            className="px-4 py-2 text-sm font-medium text-slate-600 bg-white border border-slate-200 rounded-lg hover:bg-slate-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                        >
                            Previous
                        </button>
                        <div className="flex items-center gap-1">
                            {[...Array(Math.min(5, pagination.totalPages))].map((_, i) => {
                                let pageNum;
                                if (pagination.totalPages <= 5) {
                                    pageNum = i + 1;
                                } else if (pagination.page <= 3) {
                                    pageNum = i + 1;
                                } else if (pagination.page >= pagination.totalPages - 2) {
                                    pageNum = pagination.totalPages - 4 + i;
                                } else {
                                    pageNum = pagination.page - 2 + i;
                                }

                                return (
                                    <button
                                        key={pageNum}
                                        onClick={() => handlePageChange(pageNum)}
                                        className={`w-10 h-10 flex items-center justify-center rounded-lg text-sm font-medium transition-all ${pagination.page === pageNum
                                            ? 'bg-blue-600 text-white shadow-lg shadow-blue-600/20'
                                            : 'text-slate-600 hover:bg-slate-100'
                                            }`}
                                    >
                                        {pageNum}
                                    </button>
                                );
                            })}
                        </div>
                        <button
                            onClick={() => handlePageChange(pagination.page + 1)}
                            disabled={pagination.page === pagination.totalPages}
                            className="px-4 py-2 text-sm font-medium text-slate-600 bg-white border border-slate-200 rounded-lg hover:bg-slate-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                        >
                            Next
                        </button>
                    </div>
                </div>
            </div>

            {/* Modal Optimization/Simplicity */}
            {showModal && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
                    <div className="bg-white w-full max-w-md rounded-3xl shadow-2xl p-8 relative">
                        <h2 className="text-xl font-bold mb-6">Generate Access Code</h2>
                        <form onSubmit={handleGenerate} className="space-y-6">
                            <div>
                                <label className="block text-sm font-medium text-slate-700 mb-2">Target Role</label>
                                <select
                                    className="w-full bg-slate-50 border border-slate-200 rounded-xl p-3 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                                    value={newCodeData.targetRole}
                                    onChange={(e) => setNewCodeData({ ...newCodeData, targetRole: e.target.value })}
                                >
                                    <option value="technician">Technician</option>
                                    <option value="shop">Shop (Non-USA)</option>
                                </select>
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-slate-700 mb-2">Validity Period (Days)</label>
                                <input
                                    type="number"
                                    min="1"
                                    max="90"
                                    className="w-full bg-slate-50 border border-slate-200 rounded-xl p-3 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                                    value={newCodeData.expiresInDays}
                                    onChange={(e) => setNewCodeData({ ...newCodeData, expiresInDays: parseInt(e.target.value) })}
                                />
                            </div>
                            <div className="flex gap-3 pt-4">
                                <button
                                    type="button"
                                    onClick={() => setShowModal(false)}
                                    className="flex-1 px-6 py-3 border border-slate-200 rounded-xl text-slate-600 font-medium hover:bg-slate-50"
                                >
                                    Cancel
                                </button>
                                <button
                                    type="submit"
                                    className="flex-1 px-6 py-3 bg-blue-600 text-white rounded-xl font-bold shadow-lg shadow-blue-600/20 hover:bg-blue-500"
                                >
                                    Generate
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
};

export default AccessCodes;
